// <auto-generated />
using System;
using K12QuestionGraph.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K12QuestionGraph.Api.Data.Migrations
{
    [DbContext(typeof(KqgDbContext))]
    [Migration("20260502164509_AddKnowledgeOntologyForC001")]
    partial class AddKnowledgeOntologyForC001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.AIJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_cost");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Input")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("input")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_type");

                    b.Property<string>("ModelRoute")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_route");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Result")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("result")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ai_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_jobs_idempotency_key");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_jobs_status");

                    b.ToTable("ai_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_jobs_status", "status in ('queued','running','succeeded','failed','cancelled','retry_waiting')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ManifestPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("manifest_path");

                    b.Property<string>("ManifestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manifest_sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_backup_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backup_jobs_status");

                    b.ToTable("backup_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_backup_jobs_status", "status in ('queued','running','succeeded','failed')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("application/octet-stream")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("relative_path");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("StorageScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("original")
                        .HasColumnName("storage_scope");

                    b.HasKey("Id")
                        .HasName("pk_file_assets");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_file_assets_sha256");

                    b.HasIndex("Sha256", "SizeBytes")
                        .IsUnique()
                        .HasDatabaseName("ix_file_assets_sha256_size_bytes");

                    b.HasIndex("StorageScope", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ix_file_assets_storage_scope_relative_path");

                    b.ToTable("file_assets", (string)null);
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Input")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("input")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("InputFileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_file_asset_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error_message");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_import_jobs_idempotency_key");

                    b.HasIndex("InputFileAssetId")
                        .HasDatabaseName("ix_import_jobs_input_file_asset_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_jobs_status");

                    b.ToTable("import_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_import_jobs_status", "status in ('queued','running','succeeded','failed','cancelled','retry_waiting')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("parent_child")
                        .HasColumnName("edge_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_edges");

                    b.HasIndex("TargetNodeId")
                        .HasDatabaseName("ix_knowledge_edges_target_node_id");

                    b.HasIndex("SourceNodeId", "TargetNodeId", "EdgeType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_edges_source_node_id_target_node_id_edge_type_ver");

                    b.ToTable("knowledge_edges", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_edges_not_self", "source_node_id <> target_node_id");

                            t.HasCheckConstraint("ck_knowledge_edges_type", "edge_type in ('parent_child','prerequisite','related')");

                            t.HasCheckConstraint("ck_knowledge_edges_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("KnowledgeNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_node_id");

                    b.Property<string>("MappingSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("manual")
                        .HasColumnName("mapping_source");

                    b.Property<Guid>("QuestionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_item_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_mappings");

                    b.HasIndex("KnowledgeNodeId")
                        .HasDatabaseName("ix_knowledge_mappings_knowledge_node_id");

                    b.HasIndex("MappingSource")
                        .HasDatabaseName("ix_knowledge_mappings_mapping_source");

                    b.HasIndex("QuestionItemId", "KnowledgeNodeId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_mappings_question_item_id_knowledge_node_id_versi");

                    b.ToTable("knowledge_mappings", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_mappings_confidence", "confidence is null or (confidence >= 0 and confidence <= 1)");

                            t.HasCheckConstraint("ck_knowledge_mappings_source", "mapping_source in ('manual','import','ai_suggested')");

                            t.HasCheckConstraint("ck_knowledge_mappings_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("concept")
                        .HasColumnName("node_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("junior_middle_school")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("physics")
                        .HasColumnName("subject");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_knowledge_nodes_parent_id");

                    b.HasIndex("Subject", "Stage", "Level")
                        .HasDatabaseName("ix_knowledge_nodes_subject_stage_level");

                    b.HasIndex("Subject", "Stage", "Code", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_nodes_subject_stage_code_version");

                    b.ToTable("knowledge_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_nodes_level", "level >= 1");

                            t.HasCheckConstraint("ck_knowledge_nodes_status", "status in ('draft','active','deprecated','retired')");

                            t.HasCheckConstraint("ck_knowledge_nodes_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("image")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_asset_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("question_content")
                        .HasColumnName("purpose");

                    b.Property<Guid>("QuestionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_item_id");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_region_id");

                    b.HasKey("Id")
                        .HasName("pk_question_assets");

                    b.HasIndex("FileAssetId")
                        .HasDatabaseName("ix_question_assets_file_asset_id");

                    b.HasIndex("QuestionItemId")
                        .HasDatabaseName("ix_question_assets_question_item_id");

                    b.HasIndex("SourceRegionId")
                        .HasDatabaseName("ix_question_assets_source_region_id");

                    b.ToTable("question_assets", (string)null);
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("text")
                        .HasColumnName("block_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("content")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("QuestionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("SourceRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_region_id");

                    b.HasKey("Id")
                        .HasName("pk_question_blocks");

                    b.HasIndex("BlockType")
                        .HasDatabaseName("ix_question_blocks_block_type");

                    b.HasIndex("SourceRegionId")
                        .HasDatabaseName("ix_question_blocks_source_region_id");

                    b.HasIndex("QuestionItemId", "SortOrder")
                        .HasDatabaseName("ix_question_blocks_question_item_id_sort_order");

                    b.ToTable("question_blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_blocks_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Blocks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("blocks")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<decimal?>("DefaultScore")
                        .HasColumnType("numeric")
                        .HasColumnName("default_score");

                    b.Property<double?>("DifficultyEstimated")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_estimated");

                    b.Property<double?>("DifficultyObserved")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_observed");

                    b.Property<string>("Grade")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("grade");

                    b.Property<Guid?>("PrimaryKnowledgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_knowledge_id");

                    b.Property<string>("QualitySignals")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_signals")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("question_type");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("junior_middle_school")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("physics")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_question_items");

                    b.HasIndex("PrimaryKnowledgeId")
                        .HasDatabaseName("ix_question_items_primary_knowledge_id");

                    b.HasIndex("Subject", "Stage", "Status")
                        .HasDatabaseName("ix_question_items_subject_stage_status");

                    b.ToTable("question_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_items_status", "status in ('draft','pending_review','usable','recommended','needs_improvement','paused','retired')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.ReviewQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("review_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_review_queue_items");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_review_queue_items_status");

                    b.ToTable("review_queue_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_queue_items_status", "status in ('open','resolved','dismissed')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnonymizationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("not_applicable")
                        .HasColumnName("anonymization_status");

                    b.Property<bool>("ContainsStudentPii")
                        .HasColumnType("boolean")
                        .HasColumnName("contains_student_pii");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExternalAiAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("external_ai_allowed");

                    b.Property<Guid>("FileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_asset_id");

                    b.Property<string>("LicenseOrPermission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("unknown")
                        .HasColumnName("license_or_permission");

                    b.Property<string>("OwnerScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("teacher_private")
                        .HasColumnName("owner_scope");

                    b.Property<bool>("SharingAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("sharing_allowed");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasDefaultValue("")
                        .HasColumnName("source_title");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("unknown")
                        .HasColumnName("source_type");

                    b.HasKey("Id")
                        .HasName("pk_source_documents");

                    b.HasIndex("ContainsStudentPii")
                        .HasDatabaseName("ix_source_documents_contains_student_pii");

                    b.HasIndex("FileAssetId")
                        .HasDatabaseName("ix_source_documents_file_asset_id");

                    b.HasIndex("OwnerScope")
                        .HasDatabaseName("ix_source_documents_owner_scope");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("ix_source_documents_source_type");

                    b.ToTable("source_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_documents_anonymization_status", "anonymization_status in ('none','anonymized','synthetic','not_applicable')");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.SourceRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CoordinateUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("percent")
                        .HasColumnName("coordinate_unit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("RegionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("preview")
                        .HasColumnName("region_type");

                    b.Property<string>("ScreenshotRelativePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("screenshot_relative_path");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_source_regions");

                    b.HasIndex("SourceDocumentId", "PageNumber")
                        .HasDatabaseName("ix_source_regions_source_document_id_page_number");

                    b.ToTable("source_regions", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_regions_bbox", "x >= 0 and y >= 0 and width > 0 and height > 0");

                            t.HasCheckConstraint("ck_source_regions_coordinate_unit", "coordinate_unit in ('pixel','point','percent')");

                            t.HasCheckConstraint("ck_source_regions_page_number", "page_number >= 1");
                        });
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.TeacherPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("preference_key");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("preference_value")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TeacherKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("teacher_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teacher_preferences");

                    b.HasIndex("TeacherKey", "PreferenceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_preferences_teacher_key_preference_key");

                    b.ToTable("teacher_preferences", (string)null);
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.ImportJob", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.FileAsset", null)
                        .WithMany()
                        .HasForeignKey("InputFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_file_assets_input_file_asset_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeEdge", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_edges_knowledge_nodes_source_node_id");

                    b.HasOne("K12QuestionGraph.Api.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_edges_knowledge_nodes_target_node_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeMapping", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_mappings_knowledge_nodes_knowledge_node_id");

                    b.HasOne("K12QuestionGraph.Api.Domain.QuestionItem", null)
                        .WithMany()
                        .HasForeignKey("QuestionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_mappings_question_items_question_item_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.KnowledgeNode", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_knowledge_nodes_knowledge_nodes_parent_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionAsset", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.FileAsset", null)
                        .WithMany()
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_question_assets_file_assets_file_asset_id");

                    b.HasOne("K12QuestionGraph.Api.Domain.QuestionItem", null)
                        .WithMany()
                        .HasForeignKey("QuestionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_assets_question_items_question_item_id");

                    b.HasOne("K12QuestionGraph.Api.Domain.SourceRegion", null)
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_question_assets_source_regions_source_region_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionBlock", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.QuestionItem", null)
                        .WithMany()
                        .HasForeignKey("QuestionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_blocks_question_items_question_item_id");

                    b.HasOne("K12QuestionGraph.Api.Domain.SourceRegion", null)
                        .WithMany()
                        .HasForeignKey("SourceRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_question_blocks_source_regions_source_region_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.QuestionItem", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.KnowledgeNode", null)
                        .WithMany()
                        .HasForeignKey("PrimaryKnowledgeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_question_items_knowledge_nodes_primary_knowledge_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.SourceDocument", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.FileAsset", null)
                        .WithMany()
                        .HasForeignKey("FileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_documents_file_assets_file_asset_id");
                });

            modelBuilder.Entity("K12QuestionGraph.Api.Domain.SourceRegion", b =>
                {
                    b.HasOne("K12QuestionGraph.Api.Domain.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_regions_source_documents_source_document_id");
                });
#pragma warning restore 612, 618
        }
    }
}
